#!/bin/bash

# default settings
PUSH_FLAG=""
VERSION="0.1.0"

while getopts "v:p" arg; do
  case $arg in
    p)
      PUSH_FLAG="--push"
      ;;
    v)
      VERSION=$OPTARG
      ;;
  esac
done


CMD="docker buildx build --platform linux/amd64 -t sloppycoder/vinobank-corebanking-sim:$VERSION $PUSH_FLAG ."
echo $CMD
$CMD
