kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

namespace: vinobank


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: newrelic-ini
    files:
      - newrelic.ini
