kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  - ingress.yaml

namespace: vinobank


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: newrelic-ini
    files:
      - newrelic.ini

secretGenerator:
  - name: aws-credential
    envs:
      - aws.env
