kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: newrelic-ini
    files:
      - newrelic.ini
